In [3]:
# 1
import numpy as np


In [7]:
# 2
vector = np.zeros(10)
print(vector) 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
# 3
array = np.arange(1, 11)
print(array)
memory_size= array.size * array.itemsize
print(f"Memory size of the array: {memory_size} of type float64")

[ 1  2  3  4  5  6  7  8  9 10]
Memory size of the array: 80 of type float64


In [12]:
# 4
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` 

In [14]:
# 5
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [15]:
# 6
vector_reversed = vector[::-1]
print(vector_reversed)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [16]:
# 7
matrix= np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
# 8
array= np.array([1,2,0,0,4,0])
array_nonzero = array.nonzero()
print(array_nonzero)


(array([0, 1, 4]),)


In [19]:
# 9
data=np.eye(3)
print(data)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 10
data2=np.tile(np.arange(5),(5,1))
print(data2)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [29]:
# 11
vector=np.linspace(0, 1, 12, endpoint=False)[1:-1]
print(vector)

[0.08333333 0.16666667 0.25       0.33333333 0.41666667 0.5
 0.58333333 0.66666667 0.75       0.83333333]


In [32]:
# 12
random_vector = np.random.random(10)
random_vector.sort()
print(random_vector)

[0.09108323 0.15074992 0.21750644 0.48265963 0.65317161 0.72498803
 0.76989619 0.82933308 0.88016245 0.93954986]


In [33]:
# 13
# Integer types
print("Integer types:")
for dtype in [np.int8, np.int32, np.int64]:
    info = np.iinfo(dtype)
    print(f"{dtype.__name__}: min = {info.min}, max = {info.max}")

# Floating-point types
print("\nFloating-point types:")
for dtype in [np.float32, np.float64]:
    info = np.finfo(dtype)
    print(f"{dtype.__name__}: min = {info.min}, max = {info.max}")

Integer types:
int8: min = -128, max = 127
int32: min = -2147483648, max = 2147483647
int64: min = -9223372036854775808, max = 9223372036854775807

Floating-point types:
float32: min = -3.4028234663852886e+38, max = 3.4028234663852886e+38
float64: min = -1.7976931348623157e+308, max = 1.7976931348623157e+308


In [34]:
# 14
array=np.array([1.5, 2.5, 3.5], dtype=np.float32)
array_int = array.astype(np.int32)
print(array_int)

[1 2 3]


In [ ]:
# 15
array = np.array([[1, 2, 3], [4, 5, 6]])
row_mean= np.mean(array, axis=1)
result=array - row_mean[:, np.newaxis]
print(result)



[[-1.  0.  1.]
 [-1.  0.  1.]]


In [39]:
# 16
matrix = np.array([[1, 2, 3], [4, 5, 6]])
sorted_matrix = np.sort(matrix, axis=0)
print(sorted_matrix)

[[1 2 3]
 [4 5 6]]


In [44]:
# 17
array = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
array[[0, 1]] = array[[1, 0]]
print(array)


[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [ ]:
# 18
C = np.array([0, 2, 1, 0, 3, 0, 0, 4, 0, 5])
A= np.repeat(np.arange(len(C)), C)
print(A)
np.bincount(A)

[1 1 2 4 4 4 7 7 7 7 9 9 9 9 9]


array([0, 2, 1, 0, 3, 0, 0, 4, 0, 5])