In [ ]:
#standard python list/array
marks=[10,20,30]

print(marks)

[10, 20, 30]


In [10]:
import numpy as np

np_marks=np.array([10,20,30])

print(np_marks)

[10 20 30]


In [7]:
print(np_marks[0])  #access first element
print(np_marks[1])  #access second element
print(np_marks[2])  #access third element

10
20
30


In [8]:
np_marks[0] = 100  #update first element
print(np_marks[0])  #access first element after update

100


In [9]:
#properties of numpy array
print(np_marks.shape)  #shape of the array
print(np_marks.dtype)  #data type of the array
print(np_marks.ndim)  #number of dimensions of the array
print(np_marks.size)  #number of elements in the array

(3,)
int64
1
3


In [ ]:
data=[10,20,30,40,50,60]
np_data=np.array(data)
print(np_data)


print(np_data.shape)  
print(np_data.dtype) 
print(np_data.ndim)  
print(np_data.size) 

[10 20 30 40 50 60]
(6,)
int64
1
6


In [16]:
normal=[[1,2],[3,4]]
print(normal)

[[1, 2], [3, 4]]


In [ ]:
data=np.array([[1,2],[3,4]])
print(data)

print(data.shape)  
print(data.dtype) 
print(data.ndim)  
print(data.size) 

[[1 2]
 [3 4]]
(2, 2)
int64
2
4


In [21]:
#array indexing
data=np.array([10,20,30,40,50,60])

print(data.size)

print(data[2]) 

6
30


In [23]:
normal=[[1,2],[3,4],[5,6]]

print(normal[1][0])

3


In [25]:
test=np.array([[1,2],[3,4],[5,6]])
print(test)

print(test[1,0]) #accessing element at row 1, column 0

print(test[2,1]) 

[[1 2]
 [3 4]
 [5 6]]
3
6


In [ ]:
#arrray slicing

data2=data[0:3]  #slicing the array
print(data2)  #print sliced array

last2=data[-2:]  #last two elements
print(last2)  #print last two elements

[10 20 30]
[50 60]


In [27]:
test=np.zeros([4,3])  #create a 4x3 array of zeros
print(test)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
test1=np.ones([4,3])  #create a 4x3 array of ones
print(test1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
test2=test1*5

print(test2)  #multiply each element by 5

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [32]:
test3=test1+test2
print(test3)  #add two arrays element-wise

[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [36]:
data=np.arange(0,10,2)
print(data)  #create an array with values from 0 to 10 with step 2


data2=np.linspace(0,10,5)  #create an array with 5 equally spaced values from 0 to 10
print(data2)  #print the array with equally spaced values

[0 2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]


In [49]:
#generate random numbers
data4=np.random.rand(5)  #generate 5 random numbers
print(np.floor(data4*100))  #print the random numbers

[32. 58. 33. 43. 42.]


In [50]:
data5=np.random.randint(0,100,10)  #generate 5 random integers between 0 and 100
print(data5)  #print the random integers

[31 34 80 65 93 89 34 57 20 82]


In [51]:
data=np.array([10,20,30,40,50,60])
data2=data.reshape(2,3)  #reshape the array to 2 rows and 3 columns
print(data2)  #print the reshaped array

[[10 20 30]
 [40 50 60]]


In [52]:
daat6=np.eye(5)
print(daat6)  #print the identity matrix of size 5x5

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [54]:
#extract columsn from a 2D array

data7=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(data7)


second_column = data7[:, 1]  #extract second column
print(second_column)  #print the second column

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5 8]


In [55]:
avg=np.mean(data7, axis=0)  #calculate average of each column
print(avg)  #print the average of each column

[4. 5. 6.]


In [ ]:
data7=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(data7)


#swap 2nd and 3rd column
data7[:, [1, 2]] = data7[:, [2, 1]]  #swap 2nd and 3rd column

print(data7)  #print the array after swapping columns

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 3 2]
 [4 6 5]
 [7 9 8]]


In [57]:
#square root of each element
data8 = np.sqrt(data7)  #calculate square root of each element
print(data8)  #print the square root of each element

[[1.         1.73205081 1.41421356]
 [2.         2.44948974 2.23606798]
 [2.64575131 3.         2.82842712]]


In [59]:
print(np.min(data7))
print(np.max(data7))

1
9


In [60]:
help(np.mean)  #get help on mean function

Help on _ArrayFunctionDispatcher in module numpy:

mean(
    a,
    axis=None,
    dtype=None,
    out=None,
    keepdims=<no value>,
    *,
    where=<no value>
)
    Compute the arithmetic mean along the specified axis.

    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.

    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.

        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the mean.  For in

In [61]:
test=np.array([10,20,0,40,0,60])

#find non zero indices
non_zero_indices = np.nonzero(test)  #find non-zero indices
print(non_zero_indices)  #print the non-zero indices

(array([0, 1, 3, 5]),)
