In [1]:
import numpy as np


In [7]:
# 1
data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)

data[[1,4], :] = data[[4,1], :]
print(data)


[[83 40  3 89 21]
 [99 24 39 58 88]
 [74 46 63 58 62]
 [37 55 79 93 75]
 [58 96 66 17 85]]


In [16]:
# 2
data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)
min_val = data.min()
max_val = data.max()
normalized_matrix = (data - min_val) / (max_val - min_val)
print(normalized_matrix)

[[0.66304348 0.31521739 0.90217391 0.75       1.        ]
 [0.59782609 0.38043478 0.7826087  0.59782609 0.64130435]
 [0.58695652 0.91304348 0.63043478 0.58695652 0.23913043]
 [0.         0.91304348 0.27173913 0.61956522 0.05434783]
 [0.06521739 0.82608696 0.25       0.90217391 0.79347826]]


In [17]:
# 3
data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)
mean_val = data.mean()
std_val = data.std()
z_score_data = (data - np.mean(data)) / np.std(data)
print(z_score_data)



[[-0.98445339 -1.84049981  1.6264882  -0.94165106 -0.85604642]
 [-0.72763946  0.34241857  0.51362785  2.01170909  0.04280232]
 [-0.29961625 -1.92610445  0.04280232  0.72763946  1.58368588]
 [ 0.34241857 -0.12840696  0.47082553  1.15566267 -0.94165106]
 [ 0.47082553  0.55643017  0.21401161 -1.15566267 -0.29961625]]


In [23]:
# 4
data = np.array(np.random.randint(1, 100, size=25)).reshape(5,5)
vector=data.ravel()
sub_arrays= np.array_split(vector, 5)
for sub_array in sub_arrays:
 print(sub_arrays)

[array([84, 19, 90, 85,  1], dtype=int32), array([58, 40, 21, 53, 92], dtype=int32), array([98, 99, 35,  6, 17], dtype=int32), array([17, 63, 69, 87, 49], dtype=int32), array([80, 91, 13, 88, 67], dtype=int32)]
[array([84, 19, 90, 85,  1], dtype=int32), array([58, 40, 21, 53, 92], dtype=int32), array([98, 99, 35,  6, 17], dtype=int32), array([17, 63, 69, 87, 49], dtype=int32), array([80, 91, 13, 88, 67], dtype=int32)]
[array([84, 19, 90, 85,  1], dtype=int32), array([58, 40, 21, 53, 92], dtype=int32), array([98, 99, 35,  6, 17], dtype=int32), array([17, 63, 69, 87, 49], dtype=int32), array([80, 91, 13, 88, 67], dtype=int32)]
[array([84, 19, 90, 85,  1], dtype=int32), array([58, 40, 21, 53, 92], dtype=int32), array([98, 99, 35,  6, 17], dtype=int32), array([17, 63, 69, 87, 49], dtype=int32), array([80, 91, 13, 88, 67], dtype=int32)]
[array([84, 19, 90, 85,  1], dtype=int32), array([58, 40, 21, 53, 92], dtype=int32), array([98, 99, 35,  6, 17], dtype=int32), array([17, 63, 69, 87, 49], d

In [30]:
# 5
v1 = np.array([3, 5, 6, 7, 8])
v2 = np.array([2, 4, 6, 8, 10])
dot_product = np.dot(v1, v2)
print(dot_product)

198


In [37]:
# 6
data1 = np.arange(1000, 1009).reshape(3, 3)
data2 = np.arange(1400, 1409).reshape(3, 3)
dot_product = np.dot(data1, data2)
print(dot_product)


[[4213215 4216218 4219221]
 [4225842 4228854 4231866]
 [4238469 4241490 4244511]]


In [45]:
# 7
matrix=np.eye(3)
scaled_matrix = 2 * matrix
inverse_matrix = np.linalg.inv(scaled_matrix)

print(matrix)
print(scaled_matrix)
print(inverse_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
[[0.5 0.  0. ]
 [0.  0.5 0. ]
 [0.  0.  0.5]]


In [ ]:
# 8 Eigenvalues and eigenvectors

In [ ]:
# 9 Find missing values

In [ ]:
# 10
# Replace missing values