In [56]:
import numpy as np
np_marks= np.array([10,20,30,40,50,60,70,80,90,100])
print(np_marks)

[ 10  20  30  40  50  60  70  80  90 100]


In [57]:
print(np_marks[0])  # Accessing the first element

10


In [58]:
# Exercise: Introduction to NumPy Arrays and Data Types

# 1. Creating NumPy arrays : Create a 1D NumPy array with the numbers from 10 to 20 (inclusive), and print it.
array_1d = np.arange(10, 21)
print( array_1d)

[10 11 12 13 14 15 16 17 18 19 20]


In [59]:
print(array_1d[0])  # Accessing the first element
print(array_1d[1])  # Accessing the second element

10
11


In [60]:
# array properties
print(array_1d.ndim)  # Number of dimensions
print(array_1d.shape)  # Shape of the array
print(array_1d.size)  # Total number of elements
print(array_1d.dtype)  # Data type of the elements

1
(11,)
11
int64


In [61]:
float_array = array_1d.astype('float64')
print(float_array.dtype)  # Data type of the elements after conversion

float64


In [62]:
int_array = float_array.astype('int64')
print(int_array.dtype)  # Data type of the elements after conversion

int64


In [63]:
# double element
double_array1 = int_array * 2
double_array2= float_array * 2
print(double_array1)
print(double_array2)

[20 22 24 26 28 30 32 34 36 38 40]
[20. 22. 24. 26. 28. 30. 32. 34. 36. 38. 40.]


In [64]:
# Array Indexing and Slicing
#1
index_array1d= np.array([10,11,12,13,14,15,16,17,18,19,20,21])
print(index_array1d[3])  # Accessing element at index 3

13


In [65]:
#2
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d[1,2])

6


In [66]:
#3
Array_1d=np.array([0,1,2,3,4,5,6,7,8,9,10])
print(Array_1d[2:6])  # Slicing elements from index 2 to 6 (exclusive of 6)

[2 3 4 5]


In [67]:
#4 Slice the array to extract the subarray consisting of the first two rows and the last two columns. Print the resulting subarray. 
print(array_2d[0:2,1:3])

[[2 3]
 [5 6]]


In [68]:
# Generating Values Sequences

sequence=np.arange(20, 31)
print(sequence)  # Generating a sequence of numbers from 20 to 30 (inclusive)

[20 21 22 23 24 25 26 27 28 29 30]


In [69]:
step_sequence = np.arange(10, 21, 2)
print(step_sequence)  # Generating a sequence of numbers from 10 to 20 with a step of 2

[10 12 14 16 18 20]


In [70]:
sequence1= np.linspace(0,1,5)
print(sequence1)  # Generating a sequence of 5 numbers between 0 and 1 (inclusive)

[0.   0.25 0.5  0.75 1.  ]


In [71]:
sequence2 = np.random.rand(3)
print(sequence2)  # Generating a sequence of 3 random numbers between 0 and 1

[0.41386116 0.86865707 0.62951971]


In [72]:
sequence3=np.random.randint(1,10,4)
print(sequence3)  # Generating a sequence of 4 random integers between 1 and 10 (inclusive of 1, exclusive of 10)

[4 7 7 9]


In [73]:
# Matrix Operations and Generating Values
# 1
data= np.arange(1,10)
print(data)

[1 2 3 4 5 6 7 8 9]


In [74]:
matrix1= np.reshape(data, (3, 3))
print(matrix1)  # Reshaping the 1D array into a 2D matrix with shape (3, 3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [75]:
# 2
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(matrix) 
print(matrix[2, 1]) # Accessing the element at row 2, column 1

[[10 20 30]
 [40 50 60]
 [70 80 90]]
80


In [76]:
# 3
mean_subtracted = matrix - matrix.mean(axis=1, keepdims=True)

print(mean_subtracted)

[[-10.   0.  10.]
 [-10.   0.  10.]
 [-10.   0.  10.]]


In [77]:
# 4
matrix3 = np.array([[4, 2, 3], [6, 1, 5], [7, 9, 8]])
matrix3[[0, 1]] = matrix3[[1, 0]]
print(matrix3)  # Swapping the first and second rows of the matrix

[[6 1 5]
 [4 2 3]
 [7 9 8]]


In [78]:
matrix4 = np.array([[4, 2, 3], [6, 1, 5], [7, 9, 8]])
print (matrix4)
sorted_matrix = matrix4[matrix4[:, 1].argsort()]
print(sorted_matrix)  # Sorting the matrix based on the first column

[[4 2 3]
 [6 1 5]
 [7 9 8]]
[[6 1 5]
 [4 2 3]
 [7 9 8]]


In [79]:
# swapping the first and third rows of the matrix
matrix4 = np.array([[4, 2, 3], [6, 1, 5], [7, 9, 8]])
matrix4[[0, 2]] = matrix4[[2, 0]]
print(matrix4) 

[[7 9 8]
 [6 1 5]
 [4 2 3]]


In [80]:
#  Functions and Computations in NumPy
# 1
array= np.array([1, 2, 3, 4, 5])
print(np.square(array))

[ 1  4  9 16 25]


In [81]:
# 2
array1= np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

print (np.add(array1, array2)) 
print  (np.subtract(array1, array2))
print(np.multiply(array1, array2)) 
print(np.divide(array1,array2)) # Element-wise multiplication of the two arrays

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [82]:
# 3
help(np.add)  # Displaying the documentation for the np.add function

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` 

In [87]:
# Advanced NumPy Operations

# a
array_2d = np.arange(1, 26).reshape(5, 5)
print(array_2d)  # Creating a 2D array with numbers from 1 to 25

# b
subarray = array_2d[:3, -3:]
print(subarray)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [ ]:
# c 
# Replace the last column of array2D with the numbers 10 to 14 (inclusive).
array_2d[:, -1] = np.arange(10, 15)
print(array_2d)

[[ 1  2  3  4 10]
 [ 6  7  8  9 11]
 [11 12 13 14 12]
 [16 17 18 19 13]
 [21 22 23 24 14]]


In [89]:
matrix1= np.arange(1, 10).reshape(3, 3)
matrix2=np.arange(10, 19).reshape(3, 3)
print (np.matmul(matrix1, matrix2))  # Element-wise multiplication of the two matrices




[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


In [ ]:

# element-wise multiplication: Multiply matrix1 and matrix2 element-wise.
elementwise_product = matrix1 * matrix2
print(elementwise_product)

[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


In [ ]:
# Print the transposition of matrix1.
transposed_matrix1 = matrix1.T
print(transposed_matrix1)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#  Generating Sequences and Array Indexing
sequence= np.arange(20,41)
print(sequence)  # Generating a sequence of numbers from 20 to 40 (inclusive

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [ ]:
print(sequence[sequence > 30])

[31 32 33 34 35 36 37 38 39 40]


In [ ]:
#  Understanding Bincount and Array Recreation: 

numbers = np.array([2, 2, 1, 1, 1, 0, 0, 0, 3, 3])
counts = np.bincount(numbers)
print(counts)  # Counting the occurrences of each number in the array

[3 3 2 2]


In [ ]:
recreated_array = np.repeat(np.arange(len(counts)), counts)
print(recreated_array)  # Recreating the original array from the counts

[0 0 0 1 1 1 2 2 3 3]
